api:
  url: "https://www.alphavantage.co/query"
  function: "DIGITAL_CURRENCY_DAILY"
  key: ""
  market: "USD"
  currency: "BTC"
  format: "csv"
raw_data:
  directory: "data/raw"
  format: "csv"
analysis_data:
  directory: "data/analysis"
  format: "csv"
